coverage:
  round: up
  precision: 2

codecov:
  notify:
    wait_for_ci: true
  require_ci_to_pass: true
  strict_yaml_branch: main

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
