name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
assignees:
  - ascopes
body:
  - type: markdown
    attributes:
      value: >-
        Hey there! Thanks for taking the time to fill out this bug report form.

        We just need a few details on the issue you are facing.

  - type: textarea
    id: brief-description
    attributes:
      label: Brief description
      description: >-
        Try to explain the overall nature of the problem briefly. This should include
        what you expect to happen and what actually happens.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: >-
        What are the steps to reproduce the issue? Try to give a simple numbered
        list of steps!
    validations:
      required: true

  - type: textarea
    id: error-message
    attributes:
      label: Error message
      description: >-
        Add any error message you see here. This will be formatted into a code
        block for you if provided.
      render: text

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: >-
        Please provide the trace logs for your build. This will be formatted in a code
        block automatically for you if provided.

        You can show the trace logs by passing the following flag to the Maven command:

        ```
        -Dorg.slf4j.simpleLogger.showThreadId=true
        -Dorg.slf4j.simpleLogger.showThreadName=true
        -Dorg.slf4j.simpleLogger.showShortLogName=true
        -Dorg.slf4j.simpleLogger.log.io.github.ascopes.protobufmavenplugin=trace
        ```

        Note that You may be asked to also provide logs from a run including the following
        later on, but avoid including this to begin with as it is incredibly noisy:

        ```
        -Dorg.slf4j.simpleLogger.defaultLogLevel=debug
        ```
      render: text

  - type: input
    id: os-version
    attributes:
      label: Operating system
      description: >-
        What OS are you using? On Windows, run `winver.exe`. On Linux and macOS, run
        `uname -a` and paste the output here.
    validations:
      required: true

  - type: input
    id: java-version
    attributes:
      label: JDK version
      description: >-
        What version of Java are you using?

        Run `java --version` and paste the output here
    validations:
      required: true

  - type: input
    id: maven-version
    attributes:
      label: Maven version
      description: >-
        What version of Maven are you using?

        Run `./mvnw --version` or `mvn --version` and paste the output here
    validations:
      required: true

  - type: input
    id: protobuf-maven-plugin-version
    attributes:
      label: Plugin version
      description: >-
        What version of this project are you using?

        You should have this in your POM somewhere. Failing that, it will be in your Maven logs.
    validations:
      required: true

  - type: input
    id: protoc-version
    attributes:
      label: Protoc version
      description: >-
        What version of `protoc` are you using?

        If you are using `protoc` from your system path, paste the output
        of `protoc --version` here. Otherwise, paste the version number or
        URL you provided to the `<protoc/>` parameter.
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Additional details
      description: >-
        Is there anything else we need to know? If possible, use this area
        to link to a reproduction project, too, if relevant and possible.

  - type: checkboxes
    id: checkbox-contribute
    attributes:
      label: Would you like to contribute a bugfix?
      description: >-
        If you would like to contribute this change, then that is awesome! Even if you
        are unfamiliar with the codebase, help is always welcome and we are happy to
        provide any assistance you may need!
      options:
        - label: Yes, I'd like to contribute a bugfix!
          required: false

  - type: checkboxes
    id: checkbox-confidential
    attributes:
      label: I've redacted any private information from my responses
      description: >-
        If you are working in a company, just double check you haven't leaked any sensitive
        information in the logs. Remember, everyone can see this bug report once you submit it.
      options:
        - label: Yes, there is no sensitive information here.
          required: true

  - type: markdown
    attributes:
      value: >-
        Thanks! That is all we need to know for now. We will try to get back
        to you as soon as possible if any other information is needed!
