name: Release

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Run the steps without deploying anything"
        default: false
        type: boolean

      skip-maven-central-staging:
        description: "Skip the Maven Central staging steps"
        default: false
        type: boolean

      skip-maven-central-promotion:
        description: "Skip the Maven Central promotion steps"
        default: false
        type: boolean

      skip-site-publication:
        description: "Skip the site publication steps"
        default: false
        type: boolean

      skip-github-release:
        description: "Skip the GitHub release creation steps"
        default: false
        type: boolean

      version:
        description: "Override deployment version"
        default: ""
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      pages: write

    environment:
      name: maven-central
      url: https://repo1.maven.org/maven2/io/github/ascopes/protobuf-maven-plugin

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 22
          distribution: 'temurin'
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_TOKEN
          gpg-passphrase: GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      
      - name: Configure Git
        if: ${{ ! inputs.skip-maven-central-staging }}
        run: |-
          git config user.name '${{ github.actor }}'
          git config user.email '${{ github.actor }}@users.noreply.github.com'

      - name: Determine release version details
        run: |-
          group_id="$(./mvnw help:evaluate -q -DforceStdout -Dexpression="project.groupId")"
          echo "group_id=${group_id}" >> "${GITHUB_ENV}"

          artifact_id="$(./mvnw help:evaluate -q -DforceStdout -Dexpression="project.artifactId")"
          echo "artifact_id=${artifact_id}" >> "${GITHUB_ENV}"

          if [[ '${{ inputs.version }}' == "" ]]; then
            echo "No explicit version provided, calculating next non-snapshot build from POM"
            release_version="$(./mvnw -B help:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/-SNAPSHOT//g')"
          else
            release_version='${{ inputs.version }}'
          fi
          echo "release_version=${release_version}" >> "${GITHUB_ENV}"
            
      - name: Build and run tests
        if: ${{ ! inputs.dry-run }}
        run: |-
          # Install protoc so those integration tests also run. This increases the reported
          # coverage on the generated site to a more accurate value.
          sudo apt update -q
          sudo apt install protobuf-compiler -qy
          ./mvnw clean verify site

      - name: Create staging release on Nexus
        if: ${{ ! inputs.skip-maven-central-staging }}
        run: |-
          ./mvnw -B -e \
              -DdryRun='${{ inputs.dry-run }}' \
              -DskipTests -Dinvoker.skip \
              -Darguments="-DskipTests -Dinvoker.skip" \
              -Dpassword='${{ secrets.GITHUB_TOKEN }}' \
              -DreleaseVersion="${release_version}" \
              -DsignTag=false \
              -Dtag="v${release_version}" \
              release:prepare release:perform
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Promote staging release
        if: ${{ ! inputs.dry-run && ! inputs.skip-maven-central-promotion }}
        run: |-
          ./scripts/close-nexus-repos.sh \
              -u "${OSSRH_USERNAME}" \
              -p "${OSSRH_TOKEN}" \
              -g "${group_id}" \
              -a "${artifact_id}" \
              -v "${release_version}" \
              -s "https://s01.oss.sonatype.org/"
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}

      - name: Upload site
        uses: actions/upload-pages-artifact@v3
        if: ${{ ! inputs.dry-run && ! inputs.skip-site-publication }}
        with:
          path: protobuf-maven-plugin/target/site

      - name: Deploy site
        if: ${{ ! inputs.dry-run && ! inputs.skip-site-publication }}
        uses: actions/deploy-pages@v4

      - name: Create GitHub Release
        if: ${{ ! inputs.dry-run && ! inputs.skip-github-release }}
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.release_version }}
          name: v${{ env.release_version }}
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
