name: Release New Version

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Run the steps without deploying anything"
        default: false
        type: boolean

      skip-maven-release:
        description: "Skip the Maven release and rollback steps."
        default: false
        type: boolean

      skip-pages:
        description: "Skip the creation and release of the documentation."
        default: false
        type: boolean

      skip-tests:
        description: "Skip unit and integration tests"
        default: false
        type: boolean

      version:
        description: "Override deployment version"
        default: ""
        type: string

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Initialize Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 24

      - name: Compute release version
        run: |-
          if [[ '${{ inputs.version }}' == "" ]]; then
            release_version="$(./mvnw -B help:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/-SNAPSHOT//g')"
          else
            release_version='${{ inputs.version }}'
          fi
          echo "release_version=${release_version}" >> "${GITHUB_ENV}"

  release:
    name: Release
    environment:
      name: maven-central
      url: https://repo1.maven.org/maven2/io/github/ascopes/protobuf-maven-plugin/
    runs-on: ubuntu-latest
    needs:
      - prepare

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Initialize Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_TOKEN
          gpg-passphrase: GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Install Protoc to $PATH
        run: scripts/install-protoc-to-github-runner.sh

      - name: Configure Git
        run: |-
          git config user.name '${{ github.actor }}'
          git config user.email '${{ github.actor }}@users.noreply.github.com'

      - name: Create Maven Central release
        if: ${{ ! inputs.skip-maven-release }}
        run: |-
          ./mvnw -B -e \
              -DdryRun='${{ inputs.dry-run }}' \
              -Dinvoker.skip='${{ inputs.skip-tests }}' \
              -Dpassword='${{ secrets.GITHUB_TOKEN }}' \
              -DreleaseVersion="${release_version}" \
              -DsignTag=false \
              -DskipTests='${{ inputs.skip-tests }}' \
              -Dtag="v${release_version}" \
              clean verify release:prepare release:perform
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_TOKEN: ${{ secrets.CENTRAL_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Revert Maven Central release
        if: ${{ failure() && ! inputs.skip-maven-release }}
        run: |-
          ./mvnw -B -e \
              -Dpassword='${{ secrets.GITHUB_TOKEN }}' \
              -DreleaseVersion="${release_version}" \
              -Dtag="v${release_version}" \
              release:rollback

      - name: Create GitHub release
        if: ${{ ! inputs.dry-run }}
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.release_version }}
          name: v${{ env.release_version }}
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}

  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    environment:
      name: GitHub Pages
      url: https://${{ github.actor }}.github.io/protobuf-maven-plugin
    needs:
      - prepare

    permissions:
      id-token: write
      pages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Initialize Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 24

      - name: Generate site
        if: ${{ ! inputs.skip-pages }}
        run: |-
          ./mvnw -B versions:set -DnewVersion="${release_version}"
          ./mvnw -B site -DskipTests -Dinvoker.skip

      - name: Upload site to GitHub API
        if: ${{ ! inputs.skip-pages }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: protobuf-maven-plugin/target/site

      - name: Deploy site to GitHub Pages
        if: ${{ ! inputs.skip-pages && ! inputs.dry-run }}
        uses: actions/deploy-pages@v4
