name: Pages

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version number to set.
        default: ""
        type: string

jobs:
  pages:
    name: Deploy Pages
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      pages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 22
          distribution: 'temurin'

      - name: Install dependencies
        run: sudo apt update -q && sudo apt install protobuf-compiler -qy

      - name: Set version
        if: ${{ inputs.version }}
        run: ./mvnw -B versions:set -DnewVersion="${{ inputs.version }}"

      - name: Build the site
        run: ./mvnw -B clean site -Dmaven.test.skip -Dinvoker.skip -Dcheckstyle.skip

      - name: Upload site
        uses: actions/upload-pages-artifact@v3
        with:
          path: protobuf-maven-plugin/target/site

      - name: Deploy site
        uses: actions/deploy-pages@v4

