name: Validate configuration

on:
  push:
    branches: 
      - maim
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    name: Validate scripts and config files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          check_together: 'yes'
          scandir: './scripts'

      - name: Validate codecov.yml
        shell: bash
        run: curl -vvv --fail --data-binary @- https://codecov.io/validate < codecov.yml
